# Generated by Django 4.1.7 on 2023-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('second', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Nameit',
        ),
    ]
