# Generated by Django 4.1.7 on 2023-10-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_name_delete_nameit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
